version: '3.8'
services:
  redis-node-41:
    image: redis:7.2-alpine
    container_name: redis-cluster-node-41
    network_mode: host
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: always

  redis-slave-node-41:
    image: redis:7.2-alpine
    container_name: redis-slave-node-41
    network_mode: host
    volumes:
      - ./redis-slave.conf:/usr/local/etc/redis/redis.conf
      - ./data-slave:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: always
