port 6380
cluster-enabled yes
cluster-config-file nodes-slave.conf
cluster-node-timeout 5000
appendonly yes
bind 0.0.0.0
protected-mode no
cluster-announce-ip 192.168.151.58
cluster-announce-port 6380
cluster-announce-bus-port 16380
