# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from datasource.v1 import data_source_pb2 as datasource_dot_v1_dot_data__source__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in datasource/v1/data_source_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataSourceServiceStub(object):
    """数据源微服务接口
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchData = channel.unary_unary(
                '/datasource.v1.DataSourceService/FetchData',
                request_serializer=datasource_dot_v1_dot_data__source__pb2.DataRequest.SerializeToString,
                response_deserializer=datasource_dot_v1_dot_data__source__pb2.DataResponse.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/datasource.v1.DataSourceService/GetCapabilities',
                request_serializer=datasource_dot_v1_dot_data__source__pb2.Empty.SerializeToString,
                response_deserializer=datasource_dot_v1_dot_data__source__pb2.Capabilities.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/datasource.v1.DataSourceService/HealthCheck',
                request_serializer=datasource_dot_v1_dot_data__source__pb2.Empty.SerializeToString,
                response_deserializer=datasource_dot_v1_dot_data__source__pb2.HealthStatus.FromString,
                _registered_method=True)


class DataSourceServiceServicer(object):
    """数据源微服务接口
    """

    def FetchData(self, request, context):
        """获取数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """获取服务能力
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataSourceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchData': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchData,
                    request_deserializer=datasource_dot_v1_dot_data__source__pb2.DataRequest.FromString,
                    response_serializer=datasource_dot_v1_dot_data__source__pb2.DataResponse.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=datasource_dot_v1_dot_data__source__pb2.Empty.FromString,
                    response_serializer=datasource_dot_v1_dot_data__source__pb2.Capabilities.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=datasource_dot_v1_dot_data__source__pb2.Empty.FromString,
                    response_serializer=datasource_dot_v1_dot_data__source__pb2.HealthStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datasource.v1.DataSourceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datasource.v1.DataSourceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataSourceService(object):
    """数据源微服务接口
    """

    @staticmethod
    def FetchData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datasource.v1.DataSourceService/FetchData',
            datasource_dot_v1_dot_data__source__pb2.DataRequest.SerializeToString,
            datasource_dot_v1_dot_data__source__pb2.DataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datasource.v1.DataSourceService/GetCapabilities',
            datasource_dot_v1_dot_data__source__pb2.Empty.SerializeToString,
            datasource_dot_v1_dot_data__source__pb2.Capabilities.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datasource.v1.DataSourceService/HealthCheck',
            datasource_dot_v1_dot_data__source__pb2.Empty.SerializeToString,
            datasource_dot_v1_dot_data__source__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
